export const USE_FIXTURES = __DEV__;
export const API_BASE_URL = '/api/';

export const ROUTE_TRANSITION_LEAVE = 200;
export const ROUTE_TRANSITION_SCROLL_TOP_DELAY = ROUTE_TRANSITION_LEAVE + 100;
export const ROUTE_TRANSITION_ENTER_DELAY = ROUTE_TRANSITION_SCROLL_TOP_DELAY;
export const ROUTE_TRANSITION_ENTER = 600;
